
export default {
  SERVER_DOMAIN: process.env.REACT_APP_SERVER_DOMAIN,
  SERVER_KEY: process.env.REACT_APP_SERVER_KEY,
  STRIPE_KEY: process.env.REACT_APP_STRIPE_KEY,
  AWS_REGION: process.env.REACT_APP_AWS_REGION,
  AWS_IDENTITY_POOL_ID: process.env.REACT_APP_AWS_IDENTITY_POOL_ID,
  AWS_POOL_ID: process.env.REACT_APP_AWS_POOL_ID,
  AWS_POOL_ARN: process.env.REACT_APP_AWS_POOL_ARN,
};
